# Python build file

universe = vanilla

executable = job.sh
initial_dir = $(results_dir)
log = ../../$(log_dir)/$(Process).log
output = ../../$(log_dir)/$(Process).out
error = ../../$(log_dir)/$(Process).err
arguments = $(job_script)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = runs.tar.gz, wandb.tar.gz

request_cpus = 1
request_memory = 50GB
request_disk = 50GB

# Extra GPU settings
request_gpus            = 1
Requirements            = (Target.CUDADriverVersion >= 12.1) && (Target.GPUs_GlobalMemoryMb > 30000)

# change to true if *not* using staging for checkpoints and interested in accessing GPUs beyond CHTC
+WantGPULab = true
+WantFlocking           = false
+WantGlidein            = false
+GPUJobLength           = $(job_length)

requirements = (Target.HasCHTCStaging == true)

queue 1
